{
 "title": "JMX仪表盘",
 "description": "JMX导出器监控",
 "tags": [
  "jmx",
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "任务", "query": "jmx" },
   {
    "name": "app",
    "label": "应用",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$app$node\"}, area)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$app$node\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "系统", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "状态"
    }
   ]
  },
  {
   "title": "运行状态",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "状态"
    }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "进程内存",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "常驻内存"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "虚拟内存"
    }
   ]
  },
  { "title": "垃圾回收器", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GC次数增量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC次数速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC时间增量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC时间速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "线程", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "JVM当前线程",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "当前"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "守护线程"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "死锁"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "监视器死锁"
    },
    {
     "expr": "jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "峰值"
    },
    {
     "expr": "jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "已启动总数"
    }
   ]
  },
  {
   "title": "JVM当前线程增量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "当前"
    },
    {
     "expr": "increase(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "守护线程"
    },
    {
     "expr": "increase(jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "死锁"
    },
    {
     "expr": "increase(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "监视器死锁"
    },
    {
     "expr": "increase(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "峰值"
    },
    {
     "expr": "increase(jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "已启动总数"
    }
   ]
  },
  {
   "title": "JVM当前线程速率",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "当前"
    },
    {
     "expr": "rate(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "守护线程"
    },
    {
     "expr": "rate(jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "死锁"
    },
    {
     "expr": "rate(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "监视器死锁"
    },
    {
     "expr": "rate(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "峰值"
    },
    {
     "expr": "rate(jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "已启动总数"
    }
   ]
  },
  { "title": "类加载", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "已加载类",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "当前已加载"
    },
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "已加载类增量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "当前已加载"
    },
    {
     "expr": "increase(jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "已加载类速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "当前已加载"
    },
    {
     "expr": "rate(jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "总数"
    }
   ]
  }
 ]
}